rvm:
  - 1.8.7
  - 1.9.2
  - 2.0.0
  - 2.1.0

before_script:
  - cp config/database.yml.SQLITE config/database.yml
  - git submodule init
  - git submodule update
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

branches:
  only:
    - master

notifications:
  irc: "irc.freenode.org#concerto-dev"
  email:
    recipients:
      concerto-dev@googlegroups.com
    on_success: change
    on_failure: change
