rvm:
  - 1.9.3
  - 2.1.0
env:
  - DB=sqlite
  - DB=mysql

before_script:
  - cp config/database.yml.travis config/database.yml
  - git submodule init
  - git submodule update
  - mysql -e 'create database concerto_test'
  #- RAILS_ENV=test bundle exec rake db:migrate --trace
  #- bundle exec rake db:test:prepare

after_script:
  - bundle-audit update
  - bundle-audit

branches:
  only:
    - master

notifications:
  irc: "irc.freenode.org#concerto-dev"
  email:
    recipients:
      concerto-dev@googlegroups.com
    on_success: change
    on_failure: change
