# Split context in several files.
#
# By default only one file with all translations is exported and
# no configuration is required. Your settings for asset pipeline
# are automatically recognized.
#
# If you want to split translations into several files or specify
# locale contexts that will be exported, just use this file to do
# so.
#
# For more informations about the export options with this file, please
# refer to the `Export Configuration` section in the README at :
# https://github.com/fnando/i18n-js#export-configuration
#
#
translations:
  - file: "app/assets/javascripts/i18n/translations.js"
    only: ['*.contents.*.js', '*.js', '*.time.am', '*.time.pm']
